---
name: Docs
"on":
  push:
    # Only targets main branch to avoid amplification effects of auto-fixing
    # the exact same stuff in multiple non-rebased branches.
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/workflows/.github/workflows/docs.yaml@v5.6.1

  generate-docs:
    name: Generate doc updates
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: astral-sh/setup-uv@v7.2.0
      - name: Generate dynamic doc
        run: |
          uv --no-progress run --frozen --group docs ./docs/docs_update.py
      - id: pr-metadata
        uses: kdeldycke/workflows/.github/actions/pr-metadata@v5.6.1
      - uses: peter-evans/create-pull-request@v8.0.0
        with:
          assignees: ${{ github.actor }}
          commit-message: "[autofix] Regenerate documentation"
          title: "[autofix] Regenerate documentation"
          body: ${{ steps.pr-metadata.outputs.body }}
          labels: "ðŸ“š documentation"
          branch: update-docs
