---
name: ðŸš€ Build & release
"on":
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - prepare-release
      - "renovate/**"
    paths:
      - "repomatic/**"
      - "tests/**"
      - pyproject.toml
      - uv.lock
      - .github/workflows/release.yaml
  workflow_dispatch:

jobs:

  release:
    uses: kdeldycke/repomatic/.github/workflows/release.yaml@v6.1.0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      WORKFLOW_UPDATE_GITHUB_PAT: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT }}
