---
name: Build & release
"on":
  push:
    branches:
      - main
  pull_request:
    paths:
      - "gha_utils/**"
      - "tests/**"
      - pyproject.toml
      - uv.lock
      - .github/workflows/release.yaml
  workflow_dispatch:

jobs:

  release:
    uses: kdeldycke/workflows/.github/workflows/release.yaml@v5.11.1
    secrets: inherit
