---
name: Renovate
"on":
  schedule:
    - cron: "3 17 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5
      - gha_utils/data/renovate.json5

jobs:

  renovate:
    uses: kdeldycke/workflows/.github/workflows/renovate.yaml@v5.11.1
    secrets: inherit
